### ISSUE TITLE
Doesn't work on iOS 8.1.3 + Safari

### ISSUE THREAD

**Issue by voltrevo** [richtr/NoSleep.js#1]
Steps to reproduce
1. Go to https://rawgit.com/richtr/NoSleep.js/master/example.html
2. Tap button
3. Wait ~1min without interacting with device
4. Display turns off

**Comment by richtr** [comment]
Thanks for reporting this issue.

I don't currently have any access to an iOS 8.1 device. AFAIK, NoSleep.js is supported on iOS 8.2+. Would like for someone else to independently confirm this issue on iOS 8.1 just to be sure.

**Comment by NekR** [comment]
Why only 8.2+?

**Comment by richtr** [comment]
According to https://david-smith.org/iosversionstats/ iOS version 8 accounts for only 1.5% of iOS usage worldwide.

If this is still required we should re-open as a new issue.
