### ISSUE TITLE
Cannot enable noSleep programatically on Android

### ISSUE THREAD

**Issue by nilnullzip** [richtr/NoSleep.js#10]
Thanks for this project! However, I have encountered this issue.

The demo page works fine on Android. And porting the code into my app with the button to enable noSleep also works. However, enabling noSleep via Javascript code that does not originate from a button click does not work. In my case I want the page to start with noSleep enabled.

I went so far as to include the button and use `$('#toggle').click()` to click it programatically seconds after the page was loaded. But still doesn't work. I printed `noSleep.noSleepVideo.paused` and found that the video was remaining paused despite the play() execution. I have come to the conclusion that Android inhibits the playing of video without user interaction. I suspect it is related to the same reason that autoplay is disabled:

> https://www.aerserv.com/why-does-video-autoplay-on-mobile-devices-not-work/

**Comment by iambumblehead** [comment]
@nilnullzip https://code.google.com/p/chromium/issues/detail?id=178297

Android chrome's media.play must originate from a user gesture to succeed. Methods to initiate 'fullscreen' browser mode are restricted in this way as well. 

Mobile Safari has user-restricted calls as well, but media.play is not one of them

https://developer.apple.com/library/safari/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/ControllingMediaWithJavaScript/ControllingMediaWithJavaScript.html#//apple_ref/doc/uid/TP40009523-CH3-SW13
