### ISSUE TITLE
New Safari solution

### ISSUE THREAD

**Issue by tcvth** [richtr/NoSleep.js#11]
NoSleep with the latest safari is redirecting to root of the website when the screen is off.

Problem is the window.location.href = "/" in the enable() function code for iOS

Solution appears to be in the code used for the demo, which instead uses window.location = window.location

https://richtr.github.io/NoSleep.js/NoSleep.js

**Comment by lmk123** [comment]
Hi, I fixed this issue in my fork: https://github.com/lmk123/NoSleep.js , I hope it can help you

**Comment by richtr** [comment]
Will be fixed in https://github.com/richtr/NoSleep.js/pull/33.
