### ISSUE TITLE
Does NoSleep work with ios14 and/or PWA?

### ISSUE THREAD

**Issue by lockykeaney** [richtr/NoSleep.js#112]
I'm trying to implement a WakeLock API fallback for a PWA. I've tried a few different ways to enable it, but nothing seems to react properly.

iOS14 had a lot of security updates, so I think that one of them had to do with the running of a video in the background no longer being allowed.

Has NoSleep ever worked with PWA?

**Comment by timtribers** [comment]
> Has NoSleep ever worked with PWA?

Hi @lockykeaney, yes we have used NoSleep in a production app for a couple of years now.  However, we have to use v0.8.0 - anything more recent causes problems on one platform or another.  I have not tested explicitly with iOS14 though.

**Comment by lockykeaney** [comment]
Thanks for the tip @timtribers, I downgraded to the same version as you. Unfortunately it had no effect for me.

I am sticking with the assumption that it doesn't work on iOS14 or the more recent versions of safari.
