### ISSUE TITLE
For iOS use:  window.location.href = window.location.href

### ISSUE THREAD

**Issue by nilnullzip** [richtr/NoSleep.js#12]
Currently for iOS the location reload employs `window.location.href = '/'`. But the problem is that if the phone is turned off, then the page is changed to `/` when it reawakened.

Alternatively if reload employs `window.location.href = window.location.href`, the page will remain unchanged after phone sleep. (Although it will be reloaded.) This still works to keep the phone awake.

**Comment by lmk123** [comment]
Hi, I fixed this issue in my fork: https://github.com/lmk123/NoSleep.js , I hope it can help you

**Comment by iVanilla** [comment]
关于阻止屏幕自动睡眠：
Android可以通过循环播放很短(比如1s)的视频做到(这个方法不知在iOS有没有用)，iOS据说是用定时器函数吧。

关于检测锁屏事件：
可以通过Page Visitable API实现，Android 6.0.1 Chrome和Firefox测试通过，iOS7 safari chrome都不行，不知其他iOS版本是否可行。

**Comment by Fleker** [comment]
Yes this can cause a problem if the site is being loaded anywhere other than the main index.

**Comment by richtr** [comment]
This will be updated in https://github.com/richtr/NoSleep.js/pull/33.
