### ISSUE TITLE
installing with bower pulls in older version of NoSleep.js?

### ISSUE THREAD

**Issue by bkuzma** [richtr/NoSleep.js#18]
Hey there,

I did an install using bower and it looks like my local version of NoSleep.js doesn't have the most recent [commit](https://github.com/richtr/NoSleep.js/commit/55635cb3e5ba7d99a033a279948f848a5a168906). My local version has `window.location = window.location;` instead of `window.location.href = '/';`, which results in the library not working on iOS (9.3.1). Could it be that the library version number needs to be incremented?

Great work otherwise!

-Brian

**Comment by richtr** [comment]
Bower should install the latest released version of this package. Currently that is v0.9.0 and that has parity currently with `master@HEAD` so there should no longer be an issue here.
