### ISSUE TITLE
Doesn't work on iOS Chrome 51

### ISSUE THREAD

**Issue by brunok8** [richtr/NoSleep.js#20]
Hi!

I did some tests on Android and iOS using Google Chrome 51 on both of them.
On Android works like a charm! But on iOS didn't work.
So I made some tests using Safari and the plugin works!
I did some research but I didn't succeed.
Someone had this problem too? 

Thanks!

**Comment by GeertVanWonterghem** [comment]
Works in Google Chrome 51 on iOS for me.

**Comment by yumikokh** [comment]
Same problem happened to me as well.

**Comment by fsonmez** [comment]
Same problem on latest version of Android 6+ works fine on Android 5.

**Comment by richtr** [comment]
Fixed by https://github.com/richtr/NoSleep.js/pull/32.
