### ISSUE TITLE
Breaks runtime on IE Mobile 11

### ISSUE THREAD

**Issue by leolux** [richtr/NoSleep.js#21]
The runtime breaks in NoSleep.js line 47 9 undefined. Reason is that IE cannot handle relational location updates as in line 47 "window.location.href = '/'". This seems to be a known issue http://stackoverflow.com/questions/10201809/ie-incompatability-with-window-location-href

 I have two questions:
1. why does "if (ua.iOS)" in line 44 return true for IE Mobile 11?
2. Is there any "nosleep" solution for Microsoft phones?

**Comment by leolux** [comment]
The user agent of my Microsoft phone is as follows:
"Mozilla/4.0 (compatible; MSIE 7.0; Windows Phone OS 7.0; Trident/3.1; IEMobile/7.0; Microsoft; Lumia 640 LTE"

I have no idea why the following pattern matches:
"iOS: /AppleWebKit/.test(navigator.userAgent) && /Mobile\/\w+/.test(navigator.userAgent)"

Does anybody have experience with NoSleep.js on a windwos phone?

**Comment by richtr** [comment]
Is this still something we should still try to fix?

I do not have access to any Microsoft phones so I am unable to work on this issue.

**Comment by richtr** [comment]
Closing this issue for now since it is impossible to continue development on this without access to a Microsoft phone.
