### ISSUE TITLE
Doesn't work on Android 6.0.1 + Chrome 52

### ISSUE THREAD

**Issue by guruinternetservices** [richtr/NoSleep.js#22]
Tested this using the live demo before implementation on our site and it is not working.

**Comment by jhintringer** [comment]
Same here. Android 6.0 + Chrome 52 fails.
iOS 9.3.5 with Safari works like a charm :)

**Comment by fsonmez** [comment]
Same, does not work in Android 6+

**Comment by richtr** [comment]
Fixed by https://github.com/richtr/NoSleep.js/pull/32.
