### ISSUE TITLE
Uses tons of CPU

### ISSUE THREAD

**Issue by jbardu** [richtr/NoSleep.js#23]
I haven't looked under Android or IOS but under OSX, if I change the UA to android, enabling NoSleep uses tons of CPU by coreaudiod and also the browser. At a wild guess it is playing the media file and this is chewing up CPU.

Perhaps this should be noted in the README, as having a no-sleep solution that doesn't use CPU may be desirable (it is for me).

**Comment by fsonmez** [comment]
Yes, same problem here, It even heats up the phone on Android after some time, I haven't experienced issues in IOS.

**Comment by jampy** [comment]
The problem seems to come from the media files, which are very short.

You might consider to replace the videos with those that I'm using here: https://github.com/jampy/react-wakelock/blob/master/src/android.jsx

**Comment by richtr** [comment]
I think you are right @jampy. The library now uses a slightly longer video and due to no-longer looping, it should use significantly less CPU.

https://github.com/richtr/NoSleep.js/pull/32
