### ISSUE TITLE
doesn't work on 10.2 on Safari or Chrome

### ISSUE THREAD

**Issue by eternal3000** [richtr/NoSleep.js#26]
Anyone noticed similar results? Does not seem to work on 10.2 period.

**Comment by mrmayfield** [comment]
Doesn't work for me either :|

**Comment by thyselius** [comment]
I'm still on 10.1 and it works fine. Will try 10.2.1 later tonight, will try to remember to check back and let you know how that went.

**Comment by mrmayfield** [comment]
Sorry! I was using mozilla when I was testing this, it works with safari but not chrome

**Comment by lrojas94** [comment]
hello!

Any updates on this? I need it to work on chrome :P

**Comment by richtr** [comment]
Please check out https://github.com/richtr/NoSleep.js/pull/32 and let me know if this works for you.

Closing this issue as this discussion is mostly happening in https://github.com/richtr/NoSleep.js/issues/29.
