### ISSUE TITLE
Doesn't work with iOS web app

### ISSUE THREAD

**Issue by MarianKeller** [richtr/NoSleep.js#27]
I just wrote a web app that requires the screen to turn on. This library does work nicely while the page is displayed in safari, but when I add it to the home screen and launch it from there, it won't prevent the device from entering sleep mode.

**Comment by thyselius** [comment]
Saving the DEMO page on the home screen and then tapping on it it works as expected. 

Do you really need the <meta name="apple-mobile-web-app-capable" content="yes"> tag?

**Comment by dmrschmidt** [comment]
FYI, I filed a radar for this behavior and put a copy of it up here: https://openradar.appspot.com/30184961

**Comment by GeertVanWonterghem** [comment]
Great, dmrschmidt, I would love it if I could support/ +1/ endorse your request towards Apple...
All the best!
Geert.

**Comment by unclemetz** [comment]
Any movement on this, by chance? We're really happy with how well nosleep.js works in regular mobile Safari.  But since we heavily push customers to "install" the mobile-web-app launcher, they won't see the benefit of NoSleep. Thanks!!

**Comment by vitaliyhayda** [comment]
This branch worked for me in the web app on iOS 10.3.2 (iPad)
https://github.com/richtr/NoSleep.js/tree/feature/latest-device-updates

**Comment by richtr** [comment]
Fixed by .https://github.com/richtr/NoSleep.js/pull/32.
