### ISSUE TITLE
Why not run in desktop browsers?

### ISSUE THREAD

**Issue by louisameline** [richtr/NoSleep.js#28]
Hello,
I need to prevent sleep in desktop browsers too. Is there a reason why you did not target that? Do you care for a pull request? Thanks

**Comment by louisameline** [comment]
I made it optional https://github.com/louisameline/NoSleep.js/commit/c1dcbce7f1a9a4c6f71ca7ab873a9492bcf6fecb

**Comment by richtr** [comment]
The latest release of this library works will Desktop Browsers (at least, all of Chrome/Safari/Firefox on MacOS).
