### ISSUE TITLE
Broken from iOS 10.3

### ISSUE THREAD

**Issue by vespino** [richtr/NoSleep.js#29]
I tested the script yesterday, seemed to be working perfectly. After updating to iOS 10.3 it stopped working. Hope you can find a fix for this.

**Comment by alainrostain** [comment]
Same here. We are desperately looking for a fix. WE noticed that youtube.com doesn't go into sleep on ios 10.3 when playing videos. Do we know what they are doing?

**Comment by haninaguib** [comment]
have you guys been able to find any solutions?

**Comment by vespino** [comment]
None so far.

**Comment by juziLu** [comment]
it's so embrassed T-T

**Comment by SoufianeLasri** [comment]
I tried everything (videos, audios, refreshing the page, etc...) but it didn't work
Did you guys found any clue ?

**Comment by alainrostain** [comment]
We were able to create a 16 x 16 pixel video and play it inline, to prevent auto-lock.

**Comment by SoufianeLasri** [comment]
Hi @alainrostain,

Did you create the video from the code or did you put it directly in the HTML ?
How long the video is ? Because I tried with a video created from the JS and it didn't work

And why not doing a pull request to help the others ? :)

Thanks a lot

**Comment by alainrostain** [comment]
We didn't use nosleep.js We simply created a video, hosted it on amazon, and played it inline. I'm not the developer, so I don't have more specifics than this. Hope it helps.

**Comment by SoufianeLasri** [comment]
Hi @alainrostain,

Thanks for the answer, yes it helps :)
I'll try with an inline video directly put in the HTML

**Comment by richtr** [comment]
If anyone could test if https://github.com/richtr/NoSleep.js/pull/32 works then that would be much appreciated.

kudos to @alainrostain for sharing his ideas that got me thinking about how we could finally fix this.

**Comment by vespino** [comment]
@richtr Please provide me with information on how to test it, since the code doesn't seem to be changed, right?

**Comment by richtr** [comment]
@vespino, the changes are in the branch `feature/latest-device-updates`. I've added test instructions here: https://github.com/richtr/NoSleep.js/pull/32#issuecomment-312818710.

**Comment by richtr** [comment]
Fixed by https://github.com/richtr/NoSleep.js/pull/32/.
