### ISSUE TITLE
Doesn't work on iOS 8.3 + Chrome?

### ISSUE THREAD

**Issue by zhehaowang** [richtr/NoSleep.js#3]
Steps to reproduce
1. Go to https://rawgit.com/richtr/NoSleep.js/master/example.html (UserAgent iOS 8.3, Chrome 42.0)
2. Tap button
3. Wait 1min without interacting with device (iOS Autolock set to 1min)
4. Display turns off

Worked for same version of Chrome on Android 4.4.4 and Safari on iOS 8.3;

**Comment by richtr** [comment]
I could reproduce this issue but I have not found a way to keep the screen awake in Chrome on iOS despite a lot of experimentation.

As you say, it works on most Android browsers and the default Safari browser on iOS. It seems like that is all we can aim for right now.

**Comment by adam-lynch** [comment]
@richtr you should definitely add a section to the readme about support. Right now, all we got is:

>Prevent display sleep and enable wake lock in **all Android and iOS web browsers**.

>Check out the live demo in **any Android or iOS web browser**.
