### ISSUE TITLE
Some of android device run native brouser and preverent work

### ISSUE THREAD

**Issue by fix2015** [richtr/NoSleep.js#30]
hey guys, i am very like your library, but on some device i found that when i tried enable nosleep it open native browser and preverent work of site. Did you have same bug, and do you know how we can fix it?

**Comment by richtr** [comment]
Please re-open a new issue if this is still a problem and provide the following details:

* Device Name
* Android OS version
* Browser Name
* Browser version
* Steps to reproduce the issue
* Test URLs where the issue is present
