### ISSUE TITLE
Not working on Chrome anymore.

### ISSUE THREAD

**Issue by haninaguib** [richtr/NoSleep.js#31]
Anyone notice this?

**Comment by dhrytsenko** [comment]
@haninaguib Which version of Chrome do you use?

**Comment by OtterFamily** [comment]
try swapping out event listeners on 'touchstart' for 'click' or add it in addition. if you check console on mobile, chrome throws a fit about 'touchstart' for playing the video that's in the background of NoSleep. The tutorial in readme should be changed to reflect this.

Its working for me with the following code:

```
var noSleep = new NoSleep();
window.addEventListener("touchstart", function(){enableNoSleep('touch')}, false);
window.addEventListener("click", function(){enableNoSleep('click')}, false);
function enableNoSleep(type) {
  console.log(type);
  noSleep.enable(); 
  if(type=='touch')window.removeEventListener("touchstart", enableNoSleep, false);
  if(type=='click')window.removeEventListener("click", enableNoSleep, false); 
}
```

**Comment by richtr** [comment]
Could you try https://github.com/richtr/NoSleep.js/pull/32 and report if it works on your device(s)?

It would be useful to know the following if possible too:

* Device Name
* Android OS version
* Browser Name
* Browser version

**Comment by richtr** [comment]
Fixed by https://github.com/richtr/NoSleep.js/pull/32.
