### ISSUE TITLE
don't work on Android using Chrome 

### ISSUE THREAD

**Issue by micrem73** [richtr/NoSleep.js#4]
tried the test page and a custom webpage (both works instead in IOS5).

**Comment by nikmartin** [comment]
Can confirm, on Android 5.01 and Chrome mobile browser 45.0.2454.94, the screen does go to sleep on the test page with "Wake Lock Enabled" being displayed on the button

**Comment by dpmontero** [comment]
Android 5.1.1 and Chrome mobile browser 46.0.2490.76, it works, but if you use SpeechRecognition or speechSynthesis not work. Desactivates the bip of SpeechRecognition.

Any suggestions?

**Comment by richtr** [comment]
Should on the latest versions of Chrome by https://github.com/richtr/NoSleep.js/pull/32.
