### ISSUE TITLE
Does it drains the batterie?

### ISSUE THREAD

**Issue by abimelex** [richtr/NoSleep.js#50]
Starting nosleep js seems to drain my batterie and heats the phone.
Is there any nice tool to test that on android phone? Any hints how to avoid it?

**Comment by friday** [comment]
It plays a hidden video in order to prevent sleeping. Both playing the video and running your phone with the screen on for extended durations will use extra power and heat.

So it's a good idea to disable it after you done with whichever critical operation you need nosleep for.

**Comment by richtr** [comment]
I agree with @friday. This library exists to effectively keep the screen alive and is not a perfect solution.

> Both playing the video and running your phone with the screen on for extended durations will use extra power and heat.

Naturally this will drain more battery than if the device was sitting idle with the screen off.

> Any hints how to avoid it?

To my knowledge there is no other way to enable/disable sleep lock in mobile web browsers. The W3C is working on a [Wake Lock API](https://github.com/w3c/wake-lock) specification but browser support seems to be lacking at the current time.
