### ISSUE TITLE
Not working on Chrome on Android devices?

### ISSUE THREAD

**Issue by swissdude** [richtr/NoSleep.js#52]
It's working on iOS's Safari - but on Android Chrome, it's not working?

Anyone else having this issue?

[Edit]

It works on Android's Firefox. 
On Chrome, I get a Javascript-Error.

The console says: 

NoSleep.min.js:2 Failed to execute 'play' on 'HTMLMediaElement': API can only be initiated by a user gesture.

and:

NoSleep.min.js:2 Uncaught (in promise) DOMException: play() can only be initiated by a user gesture.

[Edit 2]

I fixed the issue by calling nosleep.noSleepVideo.play(); directly from a click-Event ($('.el').on('click', function(e){ nosleep.noSleepVideo.play(); });

this of course doesn't work on older iOS devices as the code intends to do...

**Comment by marxjb** [comment]
yes this should be due to [new policies](https://webkit.org/blog/6784/new-video-policies-for-ios/) for browser to not trigger video/audio without a user click. This basically makes NoSleep in the current form useless.

**Comment by muhammadabdulrahim** [comment]
I found a workaround for S8+ and later Android devices. I [mentioned it in a comment on Issue 38](https://github.com/richtr/NoSleep.js/issues/38#issuecomment-412221909) for those curious. It isn't the most elegant solution, but it might help you solve the issue you're running into.

**Comment by richtr** [comment]
As mentioned in the [README](https://github.com/richtr/NoSleep.js/blob/master/README.md), NoSleep.js `enable` must be wrapped in a browser event initiated by a user gesture:

> // (must be wrapped in a user input event handler e.g. a mouse or touch handler)

This is an acceptable compromise that means you can enable NoSleep if/when the user clicks on your page.

It was never the intention to support non-user-gesture sleep lock. Requiring a user gesture to enable sleep lock is an acceptable UX compromise for most experiences.

Closing this issue as this is not an issue with intended usage.

**Comment by seelaman** [comment]
The green screen example does not work on Android Firefox 68.7.0

https://richtr.github.io/NoSleep.js/example
