### ISSUE TITLE
NoSleep.js trigger by auto click does not work

### ISSUE THREAD

**Issue by XIaoXlao** [richtr/NoSleep.js#53]
I know it (must be wrapped in a user input event handler e.g. a mouse or touch handler) in order to make the playvideo works. 

It works when I use finger manually click the button , but when I use jquery to auto trigger the button then the play video does not work.

And i also find out that, after i use finger click it then I implement timer to click it repeatedly with 5 sec. it works also.

But what I want is the button was hidden in display and then trigger the nosleep at background. 

I test in Iphone X.

Anyone know any solution to achieve that?

**Comment by muhammadabdulrahim** [comment]
To my knowledge, iOS does not allow this. A click must explicitly occur. One quick solution is to bind _any_ mouseclick to enable nosleep.js, but that still is dependent on a user clicking to begin with. If this is for an application like a game, try to lead the player to click ASAP (perhaps with a "click to play" button) so that an explicit user-originated click occurs.

**Comment by Candyffm** [comment]
@muhammadabdulrahim is correct. No major mobile OS supports emulated user inputs to keep the device awake by playing a video (thats what NoSleep.js is all about), it has to be a user initiated interaction. Currently, there is no other solution until the HTML5 Wake Lock API will be implemented.

**Comment by richtr** [comment]
As mentioned in the [README](https://github.com/richtr/NoSleep.js/blob/master/README.md), NoSleep.js `enable` must be wrapped in a browser event initiated by a user gesture:

> // (must be wrapped in a user input event handler e.g. a mouse or touch handler)

This is an acceptable compromise that means you can enable NoSleep if/when the user clicks on your page.

You can not _simulate_ a click and expect the same behavior as that is not considered a [_trusted_ event](https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted).

It was never the intention to support non-user-gesture sleep lock. Requiring a user gesture to enable sleep lock is an acceptable UX compromise for most experiences.

Closing this issue as this is not an issue with intended usage.
