### ISSUE TITLE
Main entry point use CommonJS and ES module entry point with the module field

### ISSUE THREAD

**Issue by jeongsd** [richtr/NoSleep.js#56]
HI i'm use NoSleep.js with [CRA](https://github.com/facebook/create-react-app)

When CRA build it throw following error 
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

I'm solve this build warnning now import `dist/NoSleep.js` file
```js
import NoSleep from 'nosleep.js/dist/NoSleep';
```

So I think main entry point use CommonJS and ES module entry point with the module field
```diff
package.json
{
...
-  "main": "src/index.js",
+  "main": "dist/NoSleep.js",
+  "module": "src/index.js",
...
}
```

**Comment by richtr** [comment]
Thanks for the input. 

This was added and merged as part of https://github.com/richtr/NoSleep.js/pull/48 and `v0.8.0` has been released https://github.com/richtr/NoSleep.js/releases/tag/v0.8.0.
