### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by Thor88** [richtr/NoSleep.js#6]
Hi I tried this on Android Lollipop and Chrome and it does not work... 
I tried the example and a custom app using NoSleep.js....
any advice?

**Comment by richtr** [comment]
We would need more details to be able to assist further here:

* Device Name
* Android OS version
* Browser Name
* Browser version
* Steps to reproduce the issue
* Test URL where issue is present

If this is still a problem please re-open a new issue on this project.
