### ISSUE TITLE
Android has other solution?

### ISSUE THREAD

**Issue by MarsCaiWORD** [richtr/NoSleep.js#74]
There are a lot of problems with playing videos. The first thing you need to do is click to play. Second, some strange bugs appear in some browsers.  
Android has other solution?

**Comment by facorread** [comment]
The purpose of the Issues tab is to notify developers and contribute work on concrete issues in the source code of NoSleep.js. You can help out by reporting issues documenting each of those strange bugs you have observed.

NoSleep.js is not a perfect package and I am sure you can Google around for other solutions for Android.

**Comment by MarsCaiWORD** [comment]
@facorread  ok , Video will have strange problems so i want to know  has other solution , Thank you for your reply

**Comment by matthewhartman** [comment]
There is another solution coming soon - Wake Lock - https://web.dev/wakelock/

**Comment by MarsCaiWORD** [comment]
@matthewhartman  I hope to support each browser

**Comment by matthewhartman** [comment]
Ah yeah, fair enough

**Comment by richtr** [comment]
Native wake lock API support was added to this library in https://github.com/richtr/NoSleep.js/pull/95. This library will then fallback to other methods if this API is unavailable.
