### ISSUE TITLE
Help for nosleep of browser

### ISSUE THREAD

**Issue by petrk94** [richtr/NoSleep.js#76]
Hi,

this looks very interesting, I require something like this for my webapp, but I need that the screen can be locked, but the browser stay alive and is not going in sleep mode, due my web app is requesting periodically over XHR data from a server and has to ring if the data which are new in database arrive on phone.
So thats the problem, I hope with Wake Lock API in future will be solved or NoSleep.js can solve it.

Do you have a idea?
Thanks

**Comment by vpalaciopbcs** [comment]
what about push notifications, would that help in your case?

**Comment by deifos** [comment]
what about using push notification?, it seems that would help in your case

**Comment by petrk94** [comment]
Hi @deifos ,
yes I solved my problem with a service worker which can receive Web push notifications from a push provider, but still Im curious whether it were at least possible.

**Comment by petrk94** [comment]
@deifos ok, Im not yet happy with it, still sometimes I dont get push notifications on my phone when its screen is locked

**Comment by deifos** [comment]
I understand what you mean, I'm building a pwa and decided to go with sms
instead of push notifications because of what you just mentioned

**Comment by petrk94** [comment]
@deifos unfortunately, thats not a good option at all due in germany we have high data privacy laws and the concerns about misuse are high for that. 
Im trying right now with a trick to solve the issue about the notifications, if it work, I will let you know, maybe it will help you too.

**Comment by deifos** [comment]
Great thank you! I'm in the validation phase of my project and testing to
see what works is part of it.

**Comment by petrk94** [comment]
@deifos 
I could solve my issue with a weird trick, but seems to work, at least I tested it with my phone for one hour and still worked. I added a iframe and audio file which running in a loop, 1 second, no sound, but playing in a loop once loaded, this seems to solve the problem with the notification and keeping the browser awake, so it will not fall in standy, maybe it will help you in your case.

**Comment by deifos** [comment]
Wao! That sounds elaborated, will have to give it a go.

Thanks for sharing.
