### ISSUE TITLE
Is this repo abandoned?

### ISSUE THREAD

**Issue by Venryx** [richtr/NoSleep.js#77]
Documentation Is:

- [ ] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

Users of this library need to know if this repository is going to be maintained or not going forward.

If it is, great -- we can wait till you have some free time.

If not, we need to know so one of us can create a fork (or be added as a maintainer of this repo), to keep the project maintained. (there are several issues that affect its functionality currently, with solutions posted in the issue comments and merge requests, but they have so far not been added)

**Comment by Venryx** [comment]
Okay, I'll take that as a no. ^_^

Anyone willing to take up the project's maintenance?

If someone comes along who's willing to do so, we'd then need to get in contact with @richtr to ask him to add that person as a maintainer of the repo.

If we're unable to contact him... well that would be unfortunate since this is the largest library/repo for this functionality. I suppose someone would need to fork it, and we'd redirect people to that fork in the answers/comments mentioning this library. (on StackOverflow and such)

**Comment by madeInLagny** [comment]
For what it's worth, there is a webcomponent WakeLock repo [here](https://github.com/madeInLagny/mil-no-sleep). Disclaimer: I am the author.

**Comment by Stevie-Ray** [comment]
Chrome 79 adds the [Wake Lock API ](https://web.dev/wakelock/) as [Origin Trials ](https://googlechrome.github.io/OriginTrials/developer-guide.html) 🎉

read more:
https://developers.google.com/web/updates/2019/12/nic79#wake-lock

**Comment by JoshuaKGoldberg** [comment]
Ping @richtr, is this still of interest to you?

@Venryx and @ViRPo did you end up reaching out?

**Comment by tinglof** [comment]
Also interested in this, @richtr do you need help? Would love to have the performance PR and the nullcheck PR merged in so I can use this via npm
