### ISSUE TITLE
Doesn't work on Samsung Galaxy s5

### ISSUE THREAD

**Issue by gravitymediallc** [richtr/NoSleep.js#8]
Just tried this in a mobile app I built. The code I used is:

noSleep = new NoSleep();

	function enableNoSleep() {
	  noSleep.enable();
	  document.removeEventListener('touchstart', enableNoSleep, false);
	}
	
	document.addEventListener('touchstart', enableNoSleep, false);

Did nothing to stop the screen from going to sleep.

**Comment by richtr** [comment]
Does it work if you wrap this instead in a click event handler? Which
browser (+ version) are you using?

**Comment by gravitymediallc** [comment]
No. I figured out why -- my mobile app is html5 and so the js doesn't work unless directly run from a browser. what i ended up doing to make it "work" is inserting a 1px 1 second silent mp4 file video html5 tag onto the page with autoplay and loop properties set. That way, it forces it to stay open :(
