### ISSUE TITLE
NoSleep.js eats a lot of CPU power in latest desktop Google Chrome

### ISSUE THREAD

**Issue by AndreasCag** [richtr/NoSleep.js#98]
* Device Name: Mac Book Pro 2017
* Device Version: - 
* Browser Name: Google Chrome
* Browser Version: 83
* NoSleep.js Version: 0.9.0

### Expected Behavior

When enabled in desktop browser, NoSleep.js doesn't cause any problems with page performance.

### Actual Behavior

When enabled in desktop browser, NoSleep.js consumes a lot of CPU power.

### How Do We Reproduce?

1. Open page in Google Chrome 83 https://richtr.github.io/NoSleep.js/example/
2. Enable Wake Lock
3. Check out how much page consumes CPU in Chrome Task Manager

![image](https://user-images.githubusercontent.com/14947036/84774771-fb333f00-afe6-11ea-833c-d5a1586618ec.png)

**Comment by Danue1** [comment]
maybe duplicate issue https://github.com/richtr/NoSleep.js/issues/66

**Comment by AndreasCag** [comment]
Oops, duplicate indeed
